#this approach developed with Josh from Zapi at Ruby hacknight

default: &default
 grades:
  - 6a
  - 6a+
  - 6b
  - 6b+
  - 6c
  - 6c+
  - 7a
  - 7a+
  - 7b
  - 7b+
  - 7c
  - 7c+
  - 8a
  - 8a+
  - 8b
  - 8b+
  - 8c
  - 8c+
  - proj
  
 ratings:
  - 0
  - 1
  - 2
  - 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
